initial commit
mythrisurabhi/DynamoDb_Sample pull request #1
Opened 2023-03-13 23:22 UTC by mythrisurabhi

2023-03-14 17:25 UTC, Qiaodan007 requested changes

2023-03-14 17:25 UTC, Qiaodan007 commented on scripts/sample_data_insert.py
> +
make sure to change the parameters to dynamic inputs later

2023-03-20 20:48 UTC, mythrisurabhi commented on scripts/sample_data_insert.py
> +
Made changes to the code and committed to feature branch.

2023-03-20 21:50 UTC, Qiaodan007 approved these changes

2023-03-23 19:08 UTC, merged